### ISSUE TITLE
Fix Bug

### ISSUE THREAD

**Issue by MrVizzyTM** [Pixelmon/Pixelmon-Language#178]
Can you figthat bug (pixelmon.чаризард.name to чаризард, чаризард = charizard. That bug for all pokemon)
![2015-06-19_20 45 24](https://cloud.githubusercontent.com/assets/7906418/8257345/91bc87ac-16c6-11e5-869e-8f459b4d58fa.png)
![2015-06-19_20 45 18](https://cloud.githubusercontent.com/assets/7906418/8257346/91bd9854-16c6-11e5-928f-066e077f6406.png)

**Comment by AnonymousRandomPerson** [comment]
I have fixed the issue for the next update, but you won't be able to experience this fix if you're still on 3.4.
