### ISSUE TITLE
"Fig Berry" ? (en_US / en_GB)

### ISSUE THREAD

**Issue by Keopha** [Pixelmon/Pixelmon-Language#365]
Hello, I was looking at en_US / en_GB files, when I saw that "Figy Berry" was named "item.FigBerry.name"
Isn't there a typo ? (Fig)

**Comment by AnonymousRandomPerson** [comment]
That is a typo that was made a while back when Figy Berries were added.

**Comment by AnonymousRandomPerson** [comment]
That said, it is an item ID that is unsafe to change, so just follow the mispelled lang code.

**Comment by Keopha** [comment]
Okay, I'll ! :) Thanks for the answer
