### ISSUE TITLE
Translators Missing in Action

### ISSUE THREAD

**Issue by Rasgnarok** [Pixelmon/Pixelmon-Language#381]
Hello @Yyiyun , @Brewer021 , @Keopha , @DanielRush , @ToklaX , @TT702 ,
This has little to do with the translation, and much more to do with the Mod itself. If you can please contact me through my Twitter, https://twitter.com/Miasku, I will be needing to chat with you concerning one of Isi's mad endeavors, which had me tasked in contacting you.

Cheers, 

Ras

**Comment by Keopha** [comment]
Hi ! Contacted you on twitter, but if you prefer we can chat on discord or Skype ! (Unfortunately my oral English isn't as good as my writing, so it'll only be by text chat)

Télécharger Outlook pour Android<https://aka.ms/ghei36>



On Sun, Aug 7, 2016 at 6:36 AM +0200, "Miasku" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @Yyiyun<https://github.com/Yyiyun> , @Brewer021<https://github.com/Brewer021> , @Keopha<https://github.com/Keopha> , @DanielRush<https://github.com/DanielRush> , @ToklaX<https://github.com/ToklaX> , @TT702<https://github.com/TT702> ,
This has little to do with the translation, and much more to do with the Mod itself. If you can please contact me through my Twitter, https://twitter.com/Miasku, I will be needing to chat with you concerning one of Isi's mad endeavors, which had me tasked in contacting you.

Cheers,

Ras

-

**Comment by ToklaX** [comment]
Hi! Only to report that I've already contacted you by Twitter!

**Comment by Brewer021** [comment]
Hi! Since i have no twitter, can you contact me on mail instead?


==============
Stefan Fjellander
stefje12@icloud.com

**Comment by Rasgnarok** [comment]
Strange enough, I do not seem to find messages from you all - care to add me on skype? _RAS_~ is my username, underscores and all.

@Brewer021 I'll email ya then.

**Comment by Keopha** [comment]
@Keodrop on twitter ^^ you followed my Old account @Keopha_

Télécharger Outlook pour Android<https://aka.ms/ghei36>



On Tue, Aug 9, 2016 at 6:28 AM +0200, "Miasku" <notifications@github.com<mailto:notifications@github.com>> wrote:


Strange enough, I do not seem to find messages from you all - care to add me on skype? RAS~ is my username, underscores and all.

@Brewer021<https://github.com/Brewer021> I'll email ya then.

-

**Comment by Keopha** [comment]
Btw I can't find you on skype, add me KeophaCG3

Télécharger Outlook pour Android<https://aka.ms/ghei36>



On Tue, Aug 9, 2016 at 6:28 AM +0200, "Miasku" <notifications@github.com<mailto:notifications@github.com>> wrote:


Strange enough, I do not seem to find messages from you all - care to add me on skype? RAS~ is my username, underscores and all.

@Brewer021<https://github.com/Brewer021> I'll email ya then.

-

**Comment by Rasgnarok** [comment]
Thanks to all that replied and filled it out, I appreciate the help!

Only missing @DanielRush now.

**Comment by Brewer021** [comment]
Where is this information aviliable?


==============
Stefan Fjellander
stefje12@icloud.com
