### ISSUE TITLE
Deprecated translation

### ISSUE THREAD

**Issue by mineme45** [Pixelmon/Pixelmon-Language#451]
Hello.
I'm updating the french translation.
I have 2000+ missing lines.
But in the english file I can see that a lot are "deprecated".
The deprecated lines are still used ?
Thanks

**Comment by Keopha** [comment]
That's kind of you, if you need any help, tell me I'll be glad to help

Le 25 janv. 2017 ? 09:59, mineme45 <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Hello.
I'm updating the french translation.
I have 2000+ missing lines.
But in the english file I can see that a lot are "deprecated".
The deprecated lines are still used ?
Thanks

-

**Comment by mineme45** [comment]
Thank you Keopha.
And thanks too for all the hard work you already done in the past for this file  :)

**Comment by mineme45** [comment]
Can be close with PR #452
Only deprecated translation are skipped.
